import { archiveListType } from '@/types/archiveList';

export const archiveListData: Record<number, archiveListType> = {
  25: {
    id: 25,
    releaseDate: '2024/12',
    title: 'Abydos Summer Time',
    isListen: true,
    trackList: [
      {
        trackName: 'RE Aoharu (Tropical House Remix)',
        isOriginalSongFlag: true,
        originalSongName: 'RE Aoharu',
        composerName: null,
      },
      {
        trackName: 'Dive into Summer (Tropical House Remix)',
        isOriginalSongFlag: true,
        originalSongName: 'Dive into Summer',
        composerName: null,
      },
      {
        trackName: 'OST 221 (Tropical House Remix)',
        isOriginalSongFlag: true,
        originalSongName: 'OST 221',
        composerName: null,
      },
      {
        trackName: 'Sugar Story (Tropical House Remix)',
        isOriginalSongFlag: true,
        originalSongName: 'Sugar Story',
        composerName: null,
      },
      {
        trackName: 'Na Na Natsu! (Tropical House Remix)',
        isOriginalSongFlag: true,
        originalSongName: 'Na Na Natsu!',
        composerName: null,
      },
      {
        trackName: 'Signal of Abydos (Tropical House Remix)',
        isOriginalSongFlag: true,
        originalSongName: 'Signal of Abydos',
        composerName: null,
      },
      {
        trackName: 'TOMODACHI SUMMER (Tropical House Remix)',
        isOriginalSongFlag: true,
        originalSongName: 'TOMODACHI SUMMER',
        composerName: null,
      },
    ],
  },
  24: {
    id: 24,
    releaseDate: '2024/08',
    title: 'Usagi Vacation',
    isListen: true,
    trackList: [
      {
        trackName: 'RE Aoharu (F.S. Alt-Rock Remix)',
        isOriginalSongFlag: true,
        originalSongName: 'RE Aoharu',
        composerName: 'シイナフユキ (群雨アンブレイラ)',
      },
      {
        trackName: 'Usagi Flap (Tropical House Remix)',
        isOriginalSongFlag: true,
        originalSongName: 'Usagi Flap',
        composerName: '敷き紙',
      },
      {
        trackName: 'Water Drop (Tropical House Remix)',
        isOriginalSongFlag: true,
        originalSongName: 'Water Drop',
        composerName: '敷き紙',
      },
      {
        trackName: 'Fall into the rabbit hole (Tropical House Remix)',
        isOriginalSongFlag: true,
        originalSongName: 'Fall into the rabbit hole',
        composerName: '敷き紙',
      },
      {
        trackName: 'Up to 21°C (Tropical House Remix)',
        isOriginalSongFlag: true,
        originalSongName: 'Up to 21°C',
        composerName: '敷き紙',
      },
      {
        trackName: 'Midsummer Cat (Tropical House Remix)',
        isOriginalSongFlag: true,
        originalSongName: 'Midsummer Cat',
        composerName: '敷き紙',
      },
    ],
  },
  23: {
    id: 23,
    releaseDate: '2024/06',
    title: 'Light purple ocean',
    isListen: true,
    trackList: [
      {
        trackName: 'Midnight Sky (2024 Remix)',
        isOriginalSongFlag: true,
        originalSongName: '天空のグリニッジ',
        composerName: null,
      },
      {
        trackName: 'Ancient Temples',
        isOriginalSongFlag: true,
        originalSongName: '古の冥界寺',
        composerName: null,
      },
      {
        trackName: 'Phantom Cat',
        isOriginalSongFlag: true,
        originalSongName: '遠野幻想物語',
        composerName: null,
      },
      {
        trackName: 'Ghost Fields',
        isOriginalSongFlag: true,
        originalSongName: '夜のデンデラ野を逝く',
        composerName: null,
      },
    ],
  },
  22: {
    id: 22,
    releaseDate: '2023/12',
    title: '便利屋68大爆発',
    isListen: true,
    trackList: [
      {
        trackName: 'Oceans Ate Kivotos',
        isOriginalSongFlag: true,
        originalSongName: 'Welcome School',
        composerName: '如水',
      },
      {
        trackName: 'Unwelcome School (Progressive House Remix)',
        isOriginalSongFlag: true,
        originalSongName: 'Unwelcome School',
        composerName: '敷き紙',
      },
      {
        trackName: 'Foolish Days (Tropical House Remix)',
        isOriginalSongFlag: true,
        originalSongName: 'Foolish Days',
        composerName: '敷き紙',
      },
      {
        trackName: 'Funky Road (UK Garage Remix)',
        isOriginalSongFlag: true,
        originalSongName: 'Funky Road',
        composerName: '敷き紙',
      },
      {
        trackName: 'Paper Company 68',
        isOriginalSongFlag: true,
        originalSongName: 'Unwelcome School',
        composerName: '香淋',
      },
      {
        trackName: 'Blue New Battle (Tropical House Remix)',
        isOriginalSongFlag: true,
        originalSongName: 'Blue New Battle',
        composerName: '敷き紙',
      },
      {
        trackName: 'Welcome School (F.S. Recollectional mix)',
        isOriginalSongFlag: true,
        originalSongName: 'Welcome School',
        composerName: 'シイナフユキ (群雨アンブレイラ)',
      },
    ],
  },
  21: {
    id: 21,
    releaseDate: '2023/10',
    title: 'フレー！フレー！先生！',
    isListen: true,
    trackList: [
      {
        trackName: 'Starting Pistol (Tropical House Remix)',
        isOriginalSongFlag: true,
        originalSongName: 'Starting Pistol',
        composerName: null,
      },
      {
        trackName: 'Shooting Athletes (UK Garage House Remix)',
        isOriginalSongFlag: true,
        originalSongName: 'Shooting Athletes',
        composerName: null,
      },
    ],
  },
  20: {
    id: 20,
    releaseDate: '2023/08',
    title: 'PERORO PERORO DREAM',
    isListen: true,
    trackList: [
      {
        trackName: 'Constant Moderato (Tropical House Remix)',
        isOriginalSongFlag: true,
        originalSongName: 'Constant Moderato',
        composerName: null,
      },
      {
        trackName: 'Irasshaimase (Tropical House Remix)',
        isOriginalSongFlag: true,
        originalSongName: 'Irasshaimase',
        composerName: null,
      },
      {
        trackName: 'Hifumi Daisuki (Tropical House Remix)',
        isOriginalSongFlag: true,
        originalSongName: 'Hifumi Daisuki',
        composerName: null,
      },
      {
        trackName: 'Connected Sky (Tropical House Remix)',
        isOriginalSongFlag: true,
        originalSongName: 'Connected Sky',
        composerName: null,
      },
      {
        trackName: 'Future Lab (Tropical House Remix)',
        isOriginalSongFlag: true,
        originalSongName: 'Future Lab',
        composerName: null,
      },
      {
        trackName: 'Shooting Stars (Tropical House Remix)',
        isOriginalSongFlag: true,
        originalSongName: 'Shooting Stars',
        composerName: null,
      },
    ],
  },
  19: {
    id: 19,
    releaseDate: '2022/12',
    title: 'like a disco',
    isListen: true,
    trackList: [
      {
        trackName: 'the beginning of night (2022 remix)',
        isOriginalSongFlag: false,
        originalSongName: '',
        composerName: null,
      },
      {
        trackName: 'walk the streets',
        isOriginalSongFlag: false,
        originalSongName: '',
        composerName: null,
      },
      {
        trackName: 'sense of buoyancy (2022 remix)',
        isOriginalSongFlag: false,
        originalSongName: '',
        composerName: null,
      },
      {
        trackName: 'you can change',
        isOriginalSongFlag: false,
        originalSongName: '',
        composerName: null,
      },
      {
        trackName: 'disco disco disco',
        isOriginalSongFlag: false,
        originalSongName: '',
        composerName: null,
      },
    ],
  },
  18: {
    id: 18,
    releaseDate: '2022/09',
    title: 'Bright green rain',
    isListen: true,
    trackList: [
      {
        trackName: 'Moon Travel',
        isOriginalSongFlag: true,
        originalSongName: '月面ツアーへようこそ',
        composerName: null,
      },
      {
        trackName: 'Drive On The Beach',
        isOriginalSongFlag: true,
        originalSongName: 'デザイアドライブ',
        composerName: null,
      },
      {
        trackName: 'Terrarium Of Satellite',
        isOriginalSongFlag: true,
        originalSongName: '衛星トリフネ',
        composerName: null,
      },
      {
        trackName: 'Sea Of Tranquility',
        isOriginalSongFlag: true,
        originalSongName: '向こう側の月',
        composerName: null,
      },
    ],
  },
  17: {
    id: 17,
    releaseDate: '2022/08',
    title: 'beginning of summer #1',
    isListen: true,
    trackList: [
      {
        trackName: 'beginning of summer AM 10:00',
        isOriginalSongFlag: false,
        originalSongName: '',
        composerName: null,
      },
      {
        trackName: 'sun light',
        isOriginalSongFlag: false,
        originalSongName: '',
        composerName: null,
      },
      {
        trackName: 'on my mind',
        isOriginalSongFlag: false,
        originalSongName: '',
        composerName: null,
      },
      {
        trackName: 'wave',
        isOriginalSongFlag: false,
        originalSongName: '',
        composerName: null,
      },
      {
        trackName: 'sandy beach',
        isOriginalSongFlag: false,
        originalSongName: '',
        composerName: null,
      },
    ],
  },
  16: {
    id: 16,
    releaseDate: '2022/01',
    title: 'Vivid blue sky',
    isListen: true,
    trackList: [
      {
        trackName: 'Midnight Sky',
        isOriginalSongFlag: true,
        originalSongName: '天空のグリニッジ',
        composerName: null,
      },
      {
        trackName: 'Jungle Satellite',
        isOriginalSongFlag: true,
        originalSongName: 'トロヤ群の密林',
        composerName: null,
      },
      {
        trackName: 'Ghost Ship',
        isOriginalSongFlag: true,
        originalSongName: 'キャプテン・ムラサ',
        composerName: null,
      },
      {
        trackName: 'Trojan Green Shrine',
        isOriginalSongFlag: true,
        originalSongName: '天鳥船神社',
        composerName: null,
      },
    ],
  },
  15: {
    id: 15,
    releaseDate: '2021/12',
    title: 'Tropical Vacation',
    isListen: true,
    trackList: [
      {
        trackName: 'Tropical Heaven',
        isOriginalSongFlag: true,
        originalSongName: '有頂天変 ～ Wonderful Heaven',
        composerName: null,
      },
      {
        trackName: 'Sky & Beach',
        isOriginalSongFlag: true,
        originalSongName: '時代親父とハイカラ少女',
        composerName: null,
      },
      {
        trackName: 'Carnival',
        isOriginalSongFlag: true,
        originalSongName: '旧地獄街道を行く',
        composerName: null,
      },
      {
        trackName: 'Tropical Ocean',
        isOriginalSongFlag: true,
        originalSongName: '黒い海に紅く ～ Legendary Fish',
        composerName: null,
      },
    ],
  },
  14: {
    id: 14,
    releaseDate: '2019/11',
    title: '異世界の秘密を曝くのはもう懲り懲りだよ〜!!!',
    isListen: true,
    trackList: [
      {
        trackName: 'ふたりの',
        isOriginalSongFlag: true,
        originalSongName: '他愛も無い二人の博物誌',
        composerName: null,
      },
      {
        trackName: 'むかしむかし',
        isOriginalSongFlag: true,
        originalSongName: '童祭 ～ Innocent Treasures',
        composerName: null,
      },
      {
        trackName: 'おおぞら',
        isOriginalSongFlag: true,
        originalSongName: '天空のグリニッジ',
        composerName: null,
      },
      {
        trackName: 'ふたりで',
        isOriginalSongFlag: true,
        originalSongName: '少女秘封倶楽部',
        composerName: null,
      },
      {
        trackName: 'よる',
        isOriginalSongFlag: true,
        originalSongName: '夜のデンデラ野を逝く',
        composerName: null,
      },
      {
        trackName: 'かふぇ',
        isOriginalSongFlag: true,
        originalSongName: '衛星カフェテラス',
        composerName: null,
      },
      {
        trackName: 'め',
        isOriginalSongFlag: true,
        originalSongName: 'Dr.レイテンシーの眠れなくなる瞳',
        composerName: null,
      },
      {
        trackName: 'びょういん',
        isOriginalSongFlag: true,
        originalSongName: '緑のサナトリウム',
        composerName: null,
      },
      {
        trackName: 'はこねこ',
        isOriginalSongFlag: true,
        originalSongName: 'シュレディンガーの化猫',
        composerName: null,
      },
      {
        trackName: 'ばけねこ',
        isOriginalSongFlag: true,
        originalSongName: '遠野幻想物語',
        composerName: null,
      },
      {
        trackName: 'でんしゃ',
        isOriginalSongFlag: true,
        originalSongName: 'ヒロシゲ36号 ～ Neo Super-Express',
        composerName: null,
      },
      {
        trackName: 'べべれけ',
        isOriginalSongFlag: true,
        originalSongName: '二日酔いの同床異夢',
        composerName: null,
      },
      {
        trackName: 'じょうき',
        isOriginalSongFlag: true,
        originalSongName: '悠久の蒸気機関',
        composerName: null,
      },
      {
        trackName: 'というお話',
        isOriginalSongFlag: true,
        originalSongName: '日本中の不思議を集めて',
        composerName: null,
      },
    ],
  },
  13: {
    id: 13,
    releaseDate: '2019/08',
    title: 'Little Sun',
    isListen: false,
    trackList: [
      {
        trackName: '8/16',
        isOriginalSongFlag: true,
        originalSongName: '幽夢 ～ Inanimate Dream',
        composerName: null,
      },
      {
        trackName: '188',
        isOriginalSongFlag: true,
        originalSongName: 'デザイアドライブ',
        composerName: null,
      },
      {
        trackName: 'SunLights',
        isOriginalSongFlag: true,
        originalSongName: '今昔幻想郷 ～ Flower Land',
        composerName: null,
      },
      {
        trackName: '賽の河原でボウリング',
        isOriginalSongFlag: true,
        originalSongName: '彼岸帰航 ～ Riverside View',
        composerName: null,
      },
      {
        trackName: '縁日を往く',
        isOriginalSongFlag: true,
        originalSongName: '旧地獄街道を行く',
        composerName: null,
      },
      {
        trackName: '地と月の１週間',
        isOriginalSongFlag: true,
        originalSongName: 'ピュアヒューリーズ ～ 心の在処',
        composerName: null,
      },
    ],
  },
  12: {
    id: 12,
    releaseDate: '2018/11',
    title: 'GALLERY',
    isListen: false,
    trackList: [
      {
        trackName: 'ひみつのふたり',
        isOriginalSongFlag: true,
        originalSongName: '少女秘封倶楽部',
        composerName: null,
      },
      {
        trackName: 'じかんのおわり',
        isOriginalSongFlag: true,
        originalSongName: '天空のグリニッジ',
        composerName: null,
      },
      {
        trackName: 'あぶないおさけ',
        isOriginalSongFlag: true,
        originalSongName: 'アウトサイダーカクテル',
        composerName: null,
      },
      {
        trackName: 'ちかにふくかぜ',
        isOriginalSongFlag: true,
        originalSongName: 'アガルタの風',
        composerName: null,
      },
      {
        trackName: 'ふるいおきもの',
        isOriginalSongFlag: true,
        originalSongName: 'イザナギオブジェクト',
        composerName: null,
      },
    ],
  },
  11: {
    id: 11,
    releaseDate: '2017/12',
    title: 'GIRL und PANZERS',
    isListen: false,
    trackList: [
      {
        trackName: "She's In A Houser!!",
        isOriginalSongFlag: true,
        originalSongName: "She's in a temper!!",
        composerName: null,
      },
      {
        trackName: 'for Lunatic Gamers',
        isOriginalSongFlag: true,
        originalSongName:
          "She's in a temper!!, 戦車むすめのみるゆめ, エキストララブ, 東方封魔録 ～ 幽幻乱舞",
        composerName: null,
      },
      {
        trackName: 'Rust',
        isOriginalSongFlag: true,
        originalSongName: "She's in a temper!!",
        composerName: null,
      },
      {
        trackName: 'Der einzig Traum',
        isOriginalSongFlag: true,
        originalSongName: "She's in a temper!!, 戦車むすめのみるゆめ",
        composerName: null,
      },
      {
        trackName: '風と共に流れtemper!!',
        isOriginalSongFlag: true,
        originalSongName: "She's in a temper!!",
        composerName: null,
      },
      {
        trackName: 'Happy Recovering ?',
        isOriginalSongFlag: true,
        originalSongName: "She's in a temper!!",
        composerName: null,
      },
      {
        trackName: 'Creator',
        isOriginalSongFlag: true,
        originalSongName: '戦車むすめのみるゆめ',
        composerName: null,
      },
      {
        trackName: '8ぴこ戦車',
        isOriginalSongFlag: true,
        originalSongName: "She's in a temper!!",
        composerName: null,
      },
      {
        trackName: 'Workshop at 3 a.m.',
        isOriginalSongFlag: true,
        originalSongName: '戦車むすめのみるゆめ',
        composerName: null,
      },
    ],
  },
  10: {
    id: 10,
    releaseDate: '2017/05',
    title: 'GAME GIRLS',
    isListen: false,
    trackList: [
      {
        trackName: 'X3 Eyes',
        isOriginalSongFlag: true,
        originalSongName: '少女さとり ～ 3rd eye',
        composerName: null,
      },
      {
        trackName: 'In Her Heart',
        isOriginalSongFlag: true,
        originalSongName: 'ハルトマンの妖怪少女',
        composerName: null,
      },
      {
        trackName: 'Bad Cat',
        isOriginalSongFlag: true,
        originalSongName: '死体旅行 ～ Be of good cheer!',
        composerName: null,
      },
      {
        trackName: "Hell's Sun",
        isOriginalSongFlag: true,
        originalSongName: '霊知の太陽信仰 ～ Nuclear Fusion',
        composerName: null,
      },
    ],
  },
  9: {
    id: 9,
    releaseDate: '2017/03',
    title: '秘封病特効薬おかわり',
    isListen: false,
    trackList: [
      {
        trackName: 'め',
        isOriginalSongFlag: true,
        originalSongName: 'Dr.レイテンシーの眠れなくなる瞳',
        composerName: null,
      },
      {
        trackName: 'でんしゃ',
        isOriginalSongFlag: true,
        originalSongName: 'ヒロシゲ36号 ~ Neo Super-Express',
        composerName: null,
      },
      {
        trackName: 'かふぇ',
        isOriginalSongFlag: true,
        originalSongName: '衛星カフェテラス',
        composerName: null,
      },
      {
        trackName: 'びょういん',
        isOriginalSongFlag: true,
        originalSongName: '緑のサナトリウム',
        composerName: null,
      },
      {
        trackName: 'じょうき',
        isOriginalSongFlag: true,
        originalSongName: '悠久の蒸気機関',
        composerName: null,
      },
    ],
  },
  8: {
    id: 8,
    releaseDate: '2016/11',
    title: '秘封病特効薬',
    isListen: false,
    trackList: [
      {
        trackName: 'ふたりの',
        isOriginalSongFlag: true,
        originalSongName: '他愛も無い二人の博物誌',
        composerName: null,
      },
      {
        trackName: 'ふたりで',
        isOriginalSongFlag: true,
        originalSongName: '少女秘封倶楽部',
        composerName: null,
      },
      {
        trackName: 'ばけねこ',
        isOriginalSongFlag: true,
        originalSongName: '遠野幻想物',
        composerName: null,
      },
      {
        trackName: 'はこねこ',
        isOriginalSongFlag: true,
        originalSongName: 'シュレディンガーの化猫',
        composerName: null,
      },
      {
        trackName: 'おおぞら',
        isOriginalSongFlag: true,
        originalSongName: '天空のグリニッジ',
        composerName: null,
      },
      {
        trackName: 'べべれけ',
        isOriginalSongFlag: true,
        originalSongName: '二日酔いの同床異夢',
        composerName: null,
      },
    ],
  },
  7: {
    id: 7,
    releaseDate: '2016/05',
    title: 'Tonight Seiga',
    isListen: false,
    trackList: [
      {
        trackName: '欲の果実',
        isOriginalSongFlag: true,
        originalSongName: 'デザイアドライブ',
        composerName: null,
      },
      {
        trackName: 'D',
        isOriginalSongFlag: true,
        originalSongName: 'デザイアドライブ',
        composerName: null,
      },
      {
        trackName: 'Desire Vortex',
        isOriginalSongFlag: true,
        originalSongName: 'デザイアドライブ',
        composerName: null,
      },
      {
        trackName: 'FEEL FOR SUPER DETH+AIR!!',
        isOriginalSongFlag: true,
        originalSongName: 'デザイアドライブ',
        composerName: null,
      },
      {
        trackName: 'なすがまま。',
        isOriginalSongFlag: true,
        originalSongName: 'デザイアドライブ',
        composerName: null,
      },
      {
        trackName: 'Fallen star',
        isOriginalSongFlag: true,
        originalSongName: 'デザイアドライブ',
        composerName: null,
      },
      {
        trackName: '西方デザイア',
        isOriginalSongFlag: true,
        originalSongName: 'デザイアドライブ',
        composerName: null,
      },
      {
        trackName: 'a bit of desires',
        isOriginalSongFlag: true,
        originalSongName: 'デザイアドライブ',
        composerName: null,
      },
      {
        trackName: 'Doomsday Desire',
        isOriginalSongFlag: true,
        originalSongName: 'デザイアドライブ',
        composerName: null,
      },
      {
        trackName: 'refrain',
        isOriginalSongFlag: true,
        originalSongName: 'デザイアドライブ',
        composerName: null,
      },
      {
        trackName: 'スピードデザイア！',
        isOriginalSongFlag: true,
        originalSongName: 'デザイアドライブ',
        composerName: null,
      },
      {
        trackName: '壁抜けダンスホール',
        isOriginalSongFlag: true,
        originalSongName: 'デザイアドライブ',
        composerName: null,
      },
      {
        trackName: 'でざいあﾋﾟｺﾋﾟｺちっぷちゅーん',
        isOriginalSongFlag: true,
        originalSongName: 'デザイアドライブ',
        composerName: null,
      },
      {
        trackName: 'runaway',
        isOriginalSongFlag: true,
        originalSongName: 'デザイアドライブ',
        composerName: null,
      },
      {
        trackName: 'Fly',
        isOriginalSongFlag: true,
        originalSongName: 'デザイアドライブ',
        composerName: null,
      },
      {
        trackName: 'The bravado',
        isOriginalSongFlag: true,
        originalSongName: 'デザイアドライブ',
        composerName: null,
      },
      {
        trackName: 'Funky Drive Night',
        isOriginalSongFlag: true,
        originalSongName: 'デザイアドライブ',
        composerName: null,
      },
      {
        trackName: 'デザイアドライブ-motif little cry monster mix-',
        isOriginalSongFlag: true,
        originalSongName: 'デザイアドライブ',
        composerName: null,
      },
      {
        trackName: '霊界ダンスフロア',
        isOriginalSongFlag: true,
        originalSongName: 'デザイアドライブ',
        composerName: null,
      },
      {
        trackName: 'Xoss Drive',
        isOriginalSongFlag: true,
        originalSongName: 'デザイアドライブ',
        composerName: null,
      },
      {
        trackName: 'Driving!!',
        isOriginalSongFlag: true,
        originalSongName: 'デザイアドライブ',
        composerName: null,
      },
    ],
  },
  6: {
    id: 6,
    releaseDate: '2015/11',
    title: 'swing for PLAY GIRLS',
    isListen: false,
    trackList: [
      {
        trackName: 'Folie & Lie',
        isOriginalSongFlag: true,
        originalSongName: '蓬莱伝説',
        composerName: null,
      },
      {
        trackName: 'Dive into the Night',
        isOriginalSongFlag: true,
        originalSongName: '天空のグリニッジ',
        composerName: null,
      },
      {
        trackName: 'Afternoon Tea',
        isOriginalSongFlag: true,
        originalSongName: '衛星カフェテラス',
        composerName: null,
      },
      {
        trackName: 'Moon Down Trip',
        isOriginalSongFlag: true,
        originalSongName: '月面ツアーへようこそ',
        composerName: null,
      },
      {
        trackName: 'Blue Sky Blue Sea',
        isOriginalSongFlag: true,
        originalSongName: '最も澄みわたる空と海',
        composerName: null,
      },
    ],
  },
  5: {
    id: 5,
    releaseDate: '2015/05',
    title: '肉',
    isListen: false,
    trackList: [
      {
        trackName: 'ぼんじり',
        isOriginalSongFlag: true,
        originalSongName: '霊知の太陽信仰 ～ Nuclear Fusion',
        composerName: null,
      },
      {
        trackName: '兎もも肉',
        isOriginalSongFlag: true,
        originalSongName: 'シンデレラケージ ～ Kagome-Kagome',
        composerName: null,
      },
      {
        trackName: 'すなずり',
        isOriginalSongFlag: true,
        originalSongName: '夜雀の歌声 ～ Night Bird',
        composerName: null,
      },
      {
        trackName: '兎むね肉',
        isOriginalSongFlag: true,
        originalSongName: '狂気の瞳 ～ Invisible Full Moon',
        composerName: null,
      },
      {
        trackName: '鳥もも肉',
        isOriginalSongFlag: true,
        originalSongName: '無間の鐘 ～ Infinite Nightmare',
        composerName: null,
      },
    ],
  },
  4: {
    id: 4,
    releaseDate: '2015/02',
    title: '赤の妹',
    isListen: false,
    trackList: [
      {
        trackName: '緋の門番',
        isOriginalSongFlag: true,
        originalSongName: '上海紅茶館 ~ Chinese Tea + α',
        composerName: null,
      },
      {
        trackName: '赫の祭り',
        isOriginalSongFlag: true,
        originalSongName: '魔法少女達の百年祭 + α',
        composerName: null,
      },
      {
        trackName: '紅の嬢',
        isOriginalSongFlag: true,
        originalSongName: '亡き王女の為のセプテット',
        composerName: null,
      },
      {
        trackName: '朱の従者',
        isOriginalSongFlag: true,
        originalSongName: 'フラワリングナイト',
        composerName: null,
      },
      {
        trackName: '赤の妹',
        isOriginalSongFlag: true,
        originalSongName: 'U.N.オーエンは彼女なのか？',
        composerName: null,
      },
    ],
  },
  3: {
    id: 3,
    releaseDate: '2014/11',
    title: 'Greenwich in the Sky',
    isListen: false,
    trackList: [
      {
        trackName: '天空のグリニッジ ～ Aerial midnight walk',
        isOriginalSongFlag: true,
        originalSongName: '天空のグリニッジ',
        composerName: null,
      },
      {
        trackName: 'Creation of Heaven and Greenwich',
        isOriginalSongFlag: true,
        originalSongName: '天空のグリニッジ',
        composerName: null,
      },
      {
        trackName: 'Duet at the observatory',
        isOriginalSongFlag: true,
        originalSongName: '天空のグリニッジ',
        composerName: null,
      },
      {
        trackName: 'Royal Observatory Rocking',
        isOriginalSongFlag: true,
        originalSongName: '天空のグリニッジ',
        composerName: null,
      },
      {
        trackName: 'メリーズパンツ',
        isOriginalSongFlag: true,
        originalSongName: '天空のグリニッジ',
        composerName: null,
      },
      {
        trackName: 'スターライト・オブザーバトリー',
        isOriginalSongFlag: true,
        originalSongName: '天空のグリニッジ',
        composerName: null,
      },
      {
        trackName: "night lounge 'ナイトラウンジ'",
        isOriginalSongFlag: true,
        originalSongName: '天空のグリニッジ',
        composerName: null,
      },
      {
        trackName: 'IronWall',
        isOriginalSongFlag: true,
        originalSongName: '天空のグリニッジ',
        composerName: null,
      },
      {
        trackName: '夜へトぶ',
        isOriginalSongFlag: true,
        originalSongName: '天空のグリニッジ',
        composerName: null,
      },
    ],
  },
};
